[package]
name = "hyper-client-pool"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
description = "Pooled Hyper Async Clients"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.3"

[dependencies.hyper]
git = "https://github.com/jwilm/hyper.git"
rev = "107ac0e3e1b869f6346f9088f1bc8ebb0b31ef1d"

[dev-dependencies]
env_logger = "0.3"
