[package]
name = "hyper-client-pool"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
description = "Pooled Hyper Async Clients"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.3"
hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"

[dev-dependencies]
env_logger = "0.3"
