[package]
name = "hyper-client-pool"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
description = "Pooled Hyper Async Clients"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.3"

[dependencies.hyper]
git = "https://github.com/DarrenTsung/hyper.git"
branch = "better-errors"

[dev-dependencies]
env_logger = "0.3"
