[package]
name = "hyper-client-pool"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
description = "Pooled Hyper Async Clients"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.3"

[dependencies.hyper]
git = "https://github.com/jwilm/hyper.git"
rev = "7505d7df8c92886201e2114ba54f94eb4a6b35c4"

[dev-dependencies]
env_logger = "0.3"
